import "./scripts/header-observers.js";
import "./scripts/burger.js";
import "./scripts/goto.js";
import "./scripts/move.js";
import "./scripts/sections-animate.js";
import "./scripts/same.js";
// import "./scripts/about-text.js";
import "./scripts/components.js";
import "./scripts/range.js";
import "./scripts/compare.js";
import "./scripts/tabs.js";
import "./scripts/product-types.js";
import "./scripts/products-select.js";
import "./scripts/spoilers.js";
import "./scripts/dialogs.js";
